name: CI/CD Pipeline

on:
  push:
    branches: ['**']
  pull_request:
    branches: [main, master]
  create:
    tags: ["v*.*.*"]

jobs:
  test:
    runs-on: ubuntu
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Run tests
      run: npm test

  build:
    runs-on: ubuntu
    needs: test
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/

  publish-package:
    runs-on: ubuntu
    needs: build
    if: ${{ gitea_event_name == 'create' && startsWith(gitea_ref, 'refs/tags/v') }}
    steps:
      - uses: actions/checkout@v4
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist/
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'

      - name: Configure npm for GitHub Packages
        run: |
            echo "@andrey-aka-skif:registry=https://npm.pkg.github.com" >> .npmrc
            echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_TOKEN }}" >> .npmrc

      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}
